name: verify

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper


    # required only if you want to verify Go code
    - name: Install dependencies (Go)
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.7'

    - name: Set up Rust (1.42.0)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.42.0-x86_64-unknown-linux-gnu
        default: true
        profile: minimal


    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all
